stages:
  - deploy

deploy:
  stage: deploy
  image: php:8.2-alpine
  only:
    - main
  before_script:
    - apk add --no-cache openssh git rsync unzip curl
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -H 165.232.75.3 >> ~/.ssh/known_hosts
  script:
    - >
      rsync -az --delete
      --exclude='.git'
      --exclude='node_modules'
      --exclude='.env'
      --exclude='storage/'
      --exclude='public/build/'
      ./ root@165.232.75.3:/var/www/laravel-app
    - ssh root@165.232.75.3 '
      cd /var/www/laravel-app &&
      composer install --no-interaction --prefer-dist --optimize-autoloader &&
      apk add --no-cache nodejs npm &&
      npm install &&
      npm run build &&
      php artisan key:generate || true &&
      php artisan migrate --force &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan storage:link || true &&
      chown -R www-data:www-data /var/www/laravel-app &&
      chmod -R 755 /var/www/laravel-app &&
      php artisan queue:restart || true
      '
