stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  only:
    - main
  before_script:
    - apk add --no-cache openssh git rsync
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -H YOUR_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - rsync -az --exclude='.git' --exclude='node_modules' --exclude='vendor' ./ root@YOUR_SERVER_IP:/var/www/laravel-app
    - ssh root@YOUR_SERVER_IP <<EOF
      cd /var/www/laravel-app
      composer install --no-interaction --prefer-dist --optimize-autoloader
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      php artisan queue:restart || true
      EOF
